language: go
services:
- docker

install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- make docker

deploy:
- provider: script
  script: make docker-push
